# frozen_string_literal: true

require "fileutils"

# Tailwind only emits utilities it finds in scanned files. Bundler installs
# FlatPack and Recording Studio outside the dummy app, and the install path
# differs between machines, so the build writes absolute @source globs here.
module TailwindGemSources
  GEM_NAMES = %w[
    flat_pack
    recording_studio
    recording_studio_accessible
    recording_studio_external_embed
    recording_studio_root_switchable
  ].freeze

  RELATIVE_GLOBS = [
    "app/components/**/*.{rb,erb}",
    "app/helpers/**/*.rb",
    "app/views/**/*.{erb,rb}"
  ].freeze

  module_function

  def css(specs: Gem.loaded_specs)
    lines = [ "/* Generated by tailwindcss:gem_sources. Do not edit. */" ]

    GEM_NAMES.each do |name|
      spec = specs[name]
      next unless spec

      root = spec.full_gem_path
      RELATIVE_GLOBS.each do |glob|
        absolute = File.join(root, glob)
        next if Dir.glob(absolute).empty?

        lines << %(@source "#{absolute}";)
      end
    end

    "#{lines.join("\n")}\n"
  end

  def write!(destination, specs: Gem.loaded_specs)
    FileUtils.mkdir_p(File.dirname(destination))
    File.write(destination, css(specs: specs))
  end
end
